{ config, lib, pkgs, ... }:

with lib;

let

  cfg = config.programs.kitty;

in

{
  options.programs.kitty = {
    enable = mkEnableOption "kitty terminal emulator";

    package = mkOption {
      type = types.package;
      default = pkgs.kitty;
      defaultText = "pkgs.kitty";
      description = "kitty package to install.";
    };
  
    config = mkOption {
      default = "";
      description = ''
        Configuration used to launch kitty
      '';
      type = types.lines;
    };
  };

  config = mkIf cfg.enable {
    xdg.configFile."kitty/kitty.conf".text = ''
      # This configuration was auto-generated by home-manager. DO NOT EDIT!
      ${cfg.config}
    '';
  };
}
